### ISSUE TITLE
reject with BAD_REQUEST

### ISSUE THREAD

**Issue by abc33867** [asararatnakar/fabric_v1_nodesample#3]
fabric-client/lib/Orderer.js:98:21
at ClientDuplexStream.<anonymous> (/home/ubuntu/souvik/hyperledger2/fabric_v1_nodesample/node_modules/fabric-client/lib/Orderer.js:98:21)
    at emitOne (events.js:96:13)
    at ClientDuplexStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ClientDuplexStream.Readable.push (_stream_readable.js:134:10)
in create channel ..

**Comment by asararatnakar** [comment]
@abc33867 
need orderer logs as per the Title , it appers to be something went wrong with the certificates.
Please provide detailed steps and orderer logs
